#!/bin/bash

cd "$HOME"

source .shrc
cat <<EOF > ".shrc_sudo"
#!/bin/sh

EOF

tr " " "\n" <<< "${SUDO_CMDS}" | while read cmd; do
	echo "Aliasing with sudo ${cmd} command"
	echo "alias ${cmd}=\"sudo \$(which ${cmd})\"" >> ".shrc_sudo"
done
