#!/bin/bash

set -euo pipefail

cd "${HOME}"

. .shrc
cat <<EOF >".shrc_sudo"
#!/bin/sh

EOF

tr " " "\n" <<<"${_SUDO_CMDS}" | while read -r cmd; do
	echo "Aliasing with sudo ${cmd} command"
	echo "alias ${cmd}=\"sudo \$(which ${cmd})\"" >>".shrc_sudo"
done
