#!/bin/bash

cd "$HOME"

sh_line='[ -e "${HOME}/.shrc" ] && . "${HOME}/.shrc"'

for sh_variant in bash zsh; do
	sh_fname=".${sh_variant}rc"
	if [ -e "${sh_fname}" ] && [[ $(grep -c "${sh_line}" "${sh_fname}") -eq 0 ]]; then
		echo "${sh_fname} is missing .shrc import: fixing it"
		echo "${sh_line}" >> "${sh_fname}"
	fi
 done
