#!/bin/bash

set -euo pipefail

cd "${HOME}"

echo "Deleting broken symlinks..."
find -L .local/bin -maxdepth 1 -type l -print -exec rm -f {} +

echo "Linking existing tools..."
find .local/share/unciae -type f -name "runner.*" | while read -r fname; do
	# file name: .local/share/unciae/category/uncia/runner.sh
	fname_bin="$(awk -F/ '{print $(NF-1)}' <<<"${fname}")" # script name: uncia
	fname_bin_rel="${fname/.local/..}"                     # path relative to .local/bin: ../share/unciae/category/uncia/runner.sh
	fname_bin_path=".local/bin/${fname_bin}"               # script target path: .local/bin/uncia
	fname_bin_parent="$(dirname "${fname}")"               # script directory: .local/share/unciae/category/uncia
	fname_bin_venv="${fname_bin_parent}/.venv"             # venv directory: .local/share/unciae/category/uncia/.venv
	fname_abs="$(realpath "${fname}")"                     # absolute path to the script: /home/$USER/.local/share/unciae/category/uncia/runner.sh
	rm -f "${fname_bin_path}"
	case "${fname##*.}" in
	sh)
		echo "Linking shell script ${fname_bin} at ${fname_bin_path}"
		ln -sf "${fname_bin_rel}" "${fname_bin_path}"
		;;
	py)
		fname_req="${fname_bin_parent}/requirements.txt"
		if [ -f "${fname_req}" ]; then
			echo "Wrapping Python script ${fname_bin} in a virtual environment at ${fname_bin_path}"
			uv venv "${fname_bin_venv}"
			# shellcheck source=/dev/null
			. "${fname_bin_venv}/bin/activate"
			uv pip install -r "${fname_req}"
			echo -e "#!/bin/bash\n$(which python) \"${fname_abs}\" \$*" >"${fname_bin_path}"
			deactivate
			chmod a+x "${fname_bin_path}"
			"${fname_bin_path}" --help >/dev/null 2>&1 || echo "${fname_bin} warmup failed"
		else
			echo "Linking Python script ${fname_bin} at ${fname_bin_path}"
			ln -sf "${fname_bin_rel}" "${fname_bin_path}"
		fi
		;;
	go)
		echo "Building Go script ${fname_bin} at ${fname_bin_path}"
		cd "${fname_bin_parent}"
		go build
		cd - >/dev/null
		mv "${fname_bin_parent}/${fname_bin}" "${fname_bin_path}"
		;;
	esac
	[ -e "${fname_bin_path}" ] && chmod a+x "${fname_bin_path}"
done
