#!/bin/bash

set -euo pipefail

cd "${HOME}/.config/yadm"

echo "Bootstrapping.."
for bootstrap_fname in bootstraps/[0-9]_bootstrap_*; do
	[[ "${bootstrap_fname}" =~ "##" ]] && continue
	echo "[${bootstrap_fname}]"
	bash "${bootstrap_fname}"
done
