#!/bin/bash

cd "$HOME"

for sh_variant in bash zsh; do
	sh_fname=".${sh_variant}rc"
	if [ "$(egrep -ce '^.*source.*/.shrc' "${sh_fname}")" -eq 0 ]; then
		echo "${sh_fname} is missing .shrc import: fixing it"
		cat <<EOF >> "${sh_fname}"

if [ -e "$HOME/.shrc" ]; then
	source "$HOME/.shrc"
fi
EOF
	fi
done
