#!/bin/bash

cd "$HOME/.config/dconf"

ls | egrep -e '([\.][a-zA-Z0-9])+' | while read dconf_fname; do
	dconf_entry="/$(sed 's/\./\//g' <<< "${dconf_fname}")/"
	echo "Loading ${dconf_fname} into ${dconf_entry} entry..."
	dconf load "${dconf_entry}" < "${dconf_fname}"
done
