name: sync

on:
  repository_dispatch:
    types: [unciae-sync]

env:
  commit_msg: "chore(unciae): sync"
  submodule_path: ".local/share/unciae"

jobs:
  unciae-update:
    if: ${{ github.event.client_payload.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ACTIONS_CLAVIS }}
      - name: Setup repository
        run: |
          git config user.email "automata@davidepucci.it" 
          git config user.name "Automata"
      - name: Sync unciae to dispatched sha
        run: |
          git submodule update --init "${submodule_path}"
          git --git-dir "${submodule_path}" checkout "${{ github.event.client_payload.sha }}"
          git commit -m "${commit_msg} (${{ github.event.client_payload.sha[:7] }})" "${submodule_path}"
      - name: Push repository
        run: |
          git push
